#!/usr/bin/env node
// Generates src/version.ts with the current version and git commit hash.
// Run as part of the build step.
import { execSync } from "child_process";
import { readFileSync, writeFileSync } from "fs";

const pkg = JSON.parse(readFileSync("package.json", "utf8"));
const version = pkg.version;

let gitCommit = "unknown";
try {
  gitCommit = execSync("git rev-parse --short HEAD", { stdio: ["pipe", "pipe", "ignore"] })
    .toString()
    .trim();
} catch {
  // Not a git repo or git not available
}

const content = `// Auto-generated by scripts/generate-version.js — do not edit manually
export const VERSION = "${version}";
export const GIT_COMMIT = "${gitCommit}";
`;

writeFileSync("src/version.ts", content);
console.log(`Generated src/version.ts — v${version} (${gitCommit})`);
