#!/usr/bin/env node
// Generates src/version.ts with the current version and git commit hash.
// Runs from three places, which is why it tolerates a hostile environment: the `build`
// script, scripts/ci.sh's prepare stage, and npm's `prepare` lifecycle — the last of which
// fires on `npm ci`, including inside a Docker layer that has copied only package.json and
// the lockfile. So neither a missing .git nor a missing src/ may throw: a failure here
// aborts `npm ci` itself, breaking install for a reason nobody would look for in this file.
import { execSync } from "child_process";
import { mkdirSync, readFileSync, writeFileSync } from "fs";

const pkg = JSON.parse(readFileSync("package.json", "utf8"));
const version = pkg.version;

let gitCommit = "unknown";
try {
  gitCommit = execSync("git rev-parse --short HEAD", { stdio: ["pipe", "pipe", "ignore"] })
    .toString()
    .trim();
} catch {
  // Not a git repo or git not available
}

const content = `// Auto-generated by scripts/generate-version.js — do not edit manually
export const VERSION = "${version}";
export const GIT_COMMIT = "${gitCommit}";
`;

mkdirSync("src", { recursive: true });
writeFileSync("src/version.ts", content);
console.log(`Generated src/version.ts — v${version} (${gitCommit})`);
