version: 2
updates:
  # Uncomment the relevant ecosystem(s) for your project

  # npm / Node.js
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "monday"
  #   open-pull-requests-limit: 5
  #   groups:
  #     dev-dependencies:
  #       dependency-type: "development"

  # Python
  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"

  # Rust
  # - package-ecosystem: "cargo"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
